/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.qq.routercenter.share.service;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RouteInfoRequest implements org.apache.thrift.TBase<RouteInfoRequest, RouteInfoRequest._Fields>, java.io.Serializable, Cloneable, Comparable<RouteInfoRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RouteInfoRequest");

  private static final org.apache.thrift.protocol.TField SID_FIELD_DESC = new org.apache.thrift.protocol.TField("sid", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField LAST_HASH_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("lastHashCode", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RouteInfoRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RouteInfoRequestTupleSchemeFactory());
  }

  public String sid; // required
  public String lastHashCode; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SID((short)1, "sid"),
    LAST_HASH_CODE((short)2, "lastHashCode");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SID
          return SID;
        case 2: // LAST_HASH_CODE
          return LAST_HASH_CODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.LAST_HASH_CODE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SID, new org.apache.thrift.meta_data.FieldMetaData("sid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAST_HASH_CODE, new org.apache.thrift.meta_data.FieldMetaData("lastHashCode", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RouteInfoRequest.class, metaDataMap);
  }

  public RouteInfoRequest() {
  }

  public RouteInfoRequest(
    String sid)
  {
    this();
    this.sid = sid;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RouteInfoRequest(RouteInfoRequest other) {
    if (other.isSetSid()) {
      this.sid = other.sid;
    }
    if (other.isSetLastHashCode()) {
      this.lastHashCode = other.lastHashCode;
    }
  }

  public RouteInfoRequest deepCopy() {
    return new RouteInfoRequest(this);
  }

  @Override
  public void clear() {
    this.sid = null;
    this.lastHashCode = null;
  }

  public String getSid() {
    return this.sid;
  }

  public RouteInfoRequest setSid(String sid) {
    this.sid = sid;
    return this;
  }

  public void unsetSid() {
    this.sid = null;
  }

  /** Returns true if field sid is set (has been assigned a value) and false otherwise */
  public boolean isSetSid() {
    return this.sid != null;
  }

  public void setSidIsSet(boolean value) {
    if (!value) {
      this.sid = null;
    }
  }

  public String getLastHashCode() {
    return this.lastHashCode;
  }

  public RouteInfoRequest setLastHashCode(String lastHashCode) {
    this.lastHashCode = lastHashCode;
    return this;
  }

  public void unsetLastHashCode() {
    this.lastHashCode = null;
  }

  /** Returns true if field lastHashCode is set (has been assigned a value) and false otherwise */
  public boolean isSetLastHashCode() {
    return this.lastHashCode != null;
  }

  public void setLastHashCodeIsSet(boolean value) {
    if (!value) {
      this.lastHashCode = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SID:
      if (value == null) {
        unsetSid();
      } else {
        setSid((String)value);
      }
      break;

    case LAST_HASH_CODE:
      if (value == null) {
        unsetLastHashCode();
      } else {
        setLastHashCode((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SID:
      return getSid();

    case LAST_HASH_CODE:
      return getLastHashCode();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SID:
      return isSetSid();
    case LAST_HASH_CODE:
      return isSetLastHashCode();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RouteInfoRequest)
      return this.equals((RouteInfoRequest)that);
    return false;
  }

  public boolean equals(RouteInfoRequest that) {
    if (that == null)
      return false;

    boolean this_present_sid = true && this.isSetSid();
    boolean that_present_sid = true && that.isSetSid();
    if (this_present_sid || that_present_sid) {
      if (!(this_present_sid && that_present_sid))
        return false;
      if (!this.sid.equals(that.sid))
        return false;
    }

    boolean this_present_lastHashCode = true && this.isSetLastHashCode();
    boolean that_present_lastHashCode = true && that.isSetLastHashCode();
    if (this_present_lastHashCode || that_present_lastHashCode) {
      if (!(this_present_lastHashCode && that_present_lastHashCode))
        return false;
      if (!this.lastHashCode.equals(that.lastHashCode))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(RouteInfoRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSid()).compareTo(other.isSetSid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sid, other.sid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastHashCode()).compareTo(other.isSetLastHashCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastHashCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastHashCode, other.lastHashCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RouteInfoRequest(");
    boolean first = true;

    sb.append("sid:");
    if (this.sid == null) {
      sb.append("null");
    } else {
      sb.append(this.sid);
    }
    first = false;
    if (isSetLastHashCode()) {
      if (!first) sb.append(", ");
      sb.append("lastHashCode:");
      if (this.lastHashCode == null) {
        sb.append("null");
      } else {
        sb.append(this.lastHashCode);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (sid == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'sid' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RouteInfoRequestStandardSchemeFactory implements SchemeFactory {
    public RouteInfoRequestStandardScheme getScheme() {
      return new RouteInfoRequestStandardScheme();
    }
  }

  private static class RouteInfoRequestStandardScheme extends StandardScheme<RouteInfoRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RouteInfoRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sid = iprot.readString();
              struct.setSidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LAST_HASH_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lastHashCode = iprot.readString();
              struct.setLastHashCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RouteInfoRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.sid != null) {
        oprot.writeFieldBegin(SID_FIELD_DESC);
        oprot.writeString(struct.sid);
        oprot.writeFieldEnd();
      }
      if (struct.lastHashCode != null) {
        if (struct.isSetLastHashCode()) {
          oprot.writeFieldBegin(LAST_HASH_CODE_FIELD_DESC);
          oprot.writeString(struct.lastHashCode);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RouteInfoRequestTupleSchemeFactory implements SchemeFactory {
    public RouteInfoRequestTupleScheme getScheme() {
      return new RouteInfoRequestTupleScheme();
    }
  }

  private static class RouteInfoRequestTupleScheme extends TupleScheme<RouteInfoRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RouteInfoRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.sid);
      BitSet optionals = new BitSet();
      if (struct.isSetLastHashCode()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetLastHashCode()) {
        oprot.writeString(struct.lastHashCode);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RouteInfoRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.sid = iprot.readString();
      struct.setSidIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.lastHashCode = iprot.readString();
        struct.setLastHashCodeIsSet(true);
      }
    }
  }

}

